<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExerciseItemSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('exercise_items')->insert([
            // =====================
            // EXERCISE 1 — Latihan Bilangan Bulat (lesson 1, UH)
            // =====================
            [
                'id'                => 1,
                'admin_id'          => null,
                'user_id'           => 1,
                'competence_id'     => 1,
                'exercise_id'       => 1,
                'exercise_type_id'  => 1,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 1,
                'question'          => 'Hasil dari 25 + (-10) adalah ...',
                'selection'         => '["<p>15<\/p>","<p>100<\/p>","<p>1<\/p>","<p>-1<\/p>"]',
                'answer'            => '["a"]',
                'is_user'           => 0,
                'created_at'        => '2025-11-18 08:26:57',
                'updated_at'        => '2025-11-18 08:26:57',
            ],
            [
                'id'                => 2,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 1,
                'exercise_id'       => 1,
                'exercise_type_id'  => 1,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 2,
                'question'          => '"<p>satu kuadrat berapa ...<\/p>"',
                'selection'         => '["<p>10<\/p>","<p>100<\/p>","<p>1<\/p>","<p>-1<\/p>"]',
                'answer'            => '["c"]',
                'is_user'           => 0,
                'created_at'        => '2021-11-10 19:29:06',
                'updated_at'        => '2022-03-14 20:57:31',
            ],

            // =====================
            // EXERCISE 2 — Pengenalan Kata Kerja (lesson 2, UH)
            // =====================
            [
                'id'                => 3,
                'admin_id'          => null,
                'user_id'           => 1,
                'competence_id'     => 2,
                'exercise_id'       => 2,
                'exercise_type_id'  => 1,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 1,
                'question'          => '"<p>Berikut ini yang merupakan keberagaman pada masyarakat Indonesia adalah <\/p>"',
                'selection'         => '["<p>Suku, agama, jenis kelamin, dan tempat tinggal<\/p>","<p>Suku, budaya, dan hak<\/p>","<p>Suku, agama, ras, budaya, dan jenis kelamin<\/p>","<p>Suku, agama, dan hukum<\/p>"]',
                'answer'            => '["c"]',
                'is_user'           => 1,
                'created_at'        => '2021-11-10 20:23:22',
                'updated_at'        => '2021-11-10 20:23:22',
            ],

            // =====================
            // EXERCISE 4 — Macam Kosa Kata (lesson 2, PTS)
            // =====================
            [
                'id'                => 4,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 1,
                'exercise_id'       => 4,
                'exercise_type_id'  => 2,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 1,
                'question'          => 'Apakah yang dimaksud kosa kata',
                'selection'         => '["<p>Suku, agama, jenis kelamin, dan tempat tinggal<\/p>","<p>Suku, budaya, dan hak<\/p>","<p>Suku, agama, ras, budaya, dan jenis kelamin<\/p>","<p>Suku, agama, dan hukum<\/p>"]',
                'answer'            => '["c"]',
                'is_user'           => 0,
                'created_at'        => '2025-12-18 13:09:42',
                'updated_at'        => '2025-12-18 13:09:42',
            ],
            [
                'id'                => 5,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 4,
                'exercise_type_id'  => 2,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 2,
                'question'          => 'Kosa kata adalah',
                'selection'         => '["<p>Suku, agama, jenis kelamin, dan tempat tinggal<\/p>","<p>Suku, budaya, dan hak<\/p>","<p>Suku, agama, ras, budaya, dan jenis kelamin<\/p>","<p>Suku, agama, dan hukum<\/p>"]',
                'answer'            => '["b"]',
                'is_user'           => 0,
                'created_at'        => '2025-12-18 13:33:17',
                'updated_at'        => '2025-12-18 13:33:17',
            ],
            [
                'id'                => 6,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 4,
                'exercise_type_id'  => 2,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 3,
                'question'          => 'Keberagaman budaya di Indonesia dapat memperkuat persatuan karena',
                'selection'         => '["<p>Mendorong sikap saling menghargai antar masyarakat<\/p>","<p>Menimbulkan perpecahan antar suku<\/p>","<p>Menghilangkan identitas daerah<\/p>","<p>Membuat masyarakat hidup sendiri-sendiri<\/p>"]',
                'answer'            => '["a"]',
                'is_user'           => 0,
                'created_at'        => '2025-12-18 13:40:00',
                'updated_at'        => '2025-12-18 13:40:00',
            ],
            [
                'id'                => 7,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 4,
                'exercise_type_id'  => 2,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 4,
                'question'          => 'Sikap yang mencerminkan toleransi dalam kehidupan sehari-hari adalah',
                'selection'         => '["<p>Menghargai perbedaan pendapat orang lain<\/p>","<p>Memaksakan pendapat pribadi<\/p>","<p>Menghindari kerja sama<\/p>","<p>Menolak perbedaan budaya<\/p>"]',
                'answer'            => '["a"]',
                'is_user'           => 0,
                'created_at'        => '2025-12-18 13:41:00',
                'updated_at'        => '2025-12-18 13:41:00',
            ],

            // =====================
            // EXERCISE 5 — Ulangan Kata Dasar (lesson 2, UH)
            // =====================
            [
                'id'                => 8,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 5,
                'exercise_type_id'  => 1,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 1,
                'question'          => 'Apa ibu kota Indonesia?',
                'selection'         => '["<p>Jakarta<\/p>","<p>Medan<\/p>","<p>Yogyakarta<\/p>","<p>Bandung<\/p>"]',
                'answer'            => '["a"]',
                'is_user'           => 0,
                'created_at'        => '2026-01-02 16:37:50',
                'updated_at'        => '2026-01-02 16:37:50',
            ],
            [
                'id'                => 9,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 5,
                'exercise_type_id'  => 1,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 2,
                'question'          => 'Kalimat yang digunakan untuk menanyakan sesuatu disebut kalimat?',
                'selection'         => '["<p>Perintah<\/p>","<p>Berita<\/p>","<p>Tanya<\/p>","<p>Seruan<\/p>"]',
                'answer'            => '["c"]',
                'is_user'           => 0,
                'created_at'        => '2026-01-02 16:43:01',
                'updated_at'        => '2026-01-02 16:43:01',
            ],
            [
                'id'                => 10,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 5,
                'exercise_type_id'  => 1,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 3,
                'question'          => 'Tanda baca yang digunakan di akhir kalimat tanya adalah?',
                'selection'         => '["<p>Titik (.)<\/p>","<p>Koma (,)<\/p>","<p>Tanda seru (!)<\/p>","<p>Tanda tanya (?)<\/p>"]',
                'answer'            => '["d"]',
                'is_user'           => 0,
                'created_at'        => '2026-01-02 16:43:01',
                'updated_at'        => '2026-01-02 16:43:01',
            ],
            [
                'id'                => 11,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 5,
                'exercise_type_id'  => 1,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 4,
                'question'          => 'Antonim dari kata "besar" adalah?',
                'selection'         => '["<p>Panjang<\/p>","<p>Tinggi<\/p>","<p>Kecil<\/p>","<p>Lebar<\/p>"]',
                'answer'            => '["c"]',
                'is_user'           => 0,
                'created_at'        => '2026-01-02 16:43:01',
                'updated_at'        => '2026-01-02 16:43:01',
            ],
            [
                'id'                => 12,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 5,
                'exercise_type_id'  => 1,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 5,
                'question'          => 'Sinonim dari kata "pandai" adalah?',
                'selection'         => '["<p>Bodoh<\/p>","<p>Cerdas<\/p>","<p>Malas<\/p>","<p>Lemah<\/p>"]',
                'answer'            => '["b"]',
                'is_user'           => 0,
                'created_at'        => '2026-01-02 16:43:01',
                'updated_at'        => '2026-01-02 16:43:01',
            ],
            [
                'id'                => 13,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 5,
                'exercise_type_id'  => 1,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 6,
                'question'          => 'Kalimat yang berisi perintah disebut kalimat?',
                'selection'         => '["<p>Tanya<\/p>","<p>Berita<\/p>","<p>Perintah<\/p>","<p>Seruan<\/p>"]',
                'answer'            => '["c"]',
                'is_user'           => 0,
                'created_at'        => '2026-01-02 16:43:01',
                'updated_at'        => '2026-01-02 16:43:01',
            ],
            [
                'id'                => 14,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 5,
                'exercise_type_id'  => 1,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 7,
                'question'          => 'Cerita yang bersifat khayalan disebut?',
                'selection'         => '["<p>Dongeng<\/p>","<p>Laporan<\/p>","<p>Berita<\/p>","<p>Pengumuman<\/p>"]',
                'answer'            => '["a"]',
                'is_user'           => 0,
                'created_at'        => '2026-01-02 16:43:01',
                'updated_at'        => '2026-01-02 16:43:01',
            ],
            [
                'id'                => 15,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 5,
                'exercise_type_id'  => 1,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 8,
                'question'          => 'Tokoh utama dalam sebuah cerita disebut?',
                'selection'         => '["<p>Latar<\/p>","<p>Alur<\/p>","<p>Tokoh utama<\/p>","<p>Amanat<\/p>"]',
                'answer'            => '["c"]',
                'is_user'           => 0,
                'created_at'        => '2026-01-02 16:43:01',
                'updated_at'        => '2026-01-02 16:43:01',
            ],
            [
                'id'                => 16,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 5,
                'exercise_type_id'  => 1,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 9,
                'question'          => 'Kalimat "Ibu memasak di dapur" termasuk kalimat?',
                'selection'         => '["<p>Perintah<\/p>","<p>Berita<\/p>","<p>Tanya<\/p>","<p>Seruan<\/p>"]',
                'answer'            => '["b"]',
                'is_user'           => 0,
                'created_at'        => '2026-01-02 16:43:01',
                'updated_at'        => '2026-01-02 16:43:01',
            ],
            [
                'id'                => 17,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 5,
                'exercise_type_id'  => 1,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 10,
                'question'          => 'Huruf kapital digunakan pada awal?',
                'selection'         => '["<p>Kata sifat<\/p>","<p>Kata kerja<\/p>","<p>Kalimat<\/p>","<p>Kata sambung<\/p>"]',
                'answer'            => '["c"]',
                'is_user'           => 0,
                'created_at'        => '2026-01-02 16:43:01',
                'updated_at'        => '2026-01-02 16:43:01',
            ],
            [
                'id'                => 18,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 5,
                'exercise_type_id'  => 1,
                'exercise_model_id' => 1,
                'exercise_choice'   => 4,
                'exercise_number'   => 11,
                'question'          => 'Pesan moral dalam sebuah cerita disebut?',
                'selection'         => '["<p>Alur<\/p>","<p>Latar<\/p>","<p>Amanat<\/p>","<p>Tokoh<\/p>"]',
                'answer'            => '["c"]',
                'is_user'           => 0,
                'created_at'        => '2026-01-02 16:43:01',
                'updated_at'        => '2026-01-02 16:43:01',
            ],

            // =====================
            // EXERCISE 6 — Soal AKM (lesson 2, AKM)
            // Campuran: pilihan ganda, pilihan ganda banyak, pernyataan, isian, uraian
            // =====================
            [
                'id'                => 19,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 6,
                'exercise_type_id'  => 4,
                'exercise_model_id' => 1, // Pilihan Ganda
                'exercise_choice'   => 4,
                'exercise_number'   => 1,
                'question'          => 'Hasil dari 12 x 5 adalah ...',
                'selection'         => '["<p>60<\/p>","<p>50<\/p>","<p>65<\/p>","<p>55<\/p>"]',
                'answer'            => '["a"]',
                'is_user'           => 0,
                'created_at'        => '2026-02-25 08:33:29',
                'updated_at'        => '2026-02-25 08:33:29',
            ],
            [
                'id'                => 20,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 6,
                'exercise_type_id'  => 4,
                'exercise_model_id' => 2, // Pilihan Ganda Banyak
                'exercise_choice'   => 5,
                'exercise_number'   => 2,
                'question'          => 'Manakah bilangan prima berikut ini?',
                'selection'         => '["<p>2<\/p>","<p>4<\/p>","<p>5<\/p>","<p>9<\/p>","<p>11<\/p>"]',
                'answer'            => '["a","c","e"]',
                'is_user'           => 0,
                'created_at'        => '2026-02-25 08:35:35',
                'updated_at'        => '2026-02-25 08:35:35',
            ],
            [
                'id'                => 21,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 6,
                'exercise_type_id'  => 4,
                'exercise_model_id' => 3, // Pernyataan (true/false)
                'exercise_choice'   => 2,
                'exercise_number'   => 3,
                'question'          => 'Pernyataan: 0 adalah bilangan genap.',
                'selection'         => '["<p>Benar<\/p>","<p>Salah<\/p>"]',
                'answer'            => '["a"]',
                'is_user'           => 0,
                'created_at'        => '2026-02-25 12:41:14',
                'updated_at'        => '2026-02-25 12:41:14',
            ],
            [
                'id'                => 22,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 2,
                'exercise_id'       => 6,
                'exercise_type_id'  => 4,
                'exercise_model_id' => 4, // Isian
                'exercise_choice'   => 0,
                'exercise_number'   => 4,
                'question'          => 'Sebutkan hasil dari 7 + 8!',
                'selection'         => null,
                'answer'            => '["15"]',
                'is_user'           => 0,
                'created_at'        => '2026-02-25 12:43:09',
                'updated_at'        => '2026-02-25 12:43:09',
            ],
            [
                'id'                => 23,
                'admin_id'          => 1,
                'user_id'           => null,
                'competence_id'     => 1,
                'exercise_id'       => 6,
                'exercise_type_id'  => 4,
                'exercise_model_id' => 5, // Uraian (essay)
                'exercise_choice'   => 0,
                'exercise_number'   => 5,
                'question'          => 'Jelaskan perbedaan bilangan prima dan komposit!',
                'selection'         => null,
                'answer'            => '["Bilangan prima adalah bilangan yang hanya memiliki dua faktor yaitu 1 dan dirinya sendiri."]',
                'is_user'           => 0,
                'created_at'        => '2026-02-25 12:44:21',
                'updated_at'        => '2026-02-25 12:44:21',
            ],
        ]);
    }
}
